In [6]:
import numpy as np
import pandas as pd

### series of 1-D array

In [7]:
S = pd.Series([10,20,30,40])
print(S)

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
pop = pd.Series([1444,1393,323,278],
                index=["India","China","USA","Indoneasia"],
                name = "Popoulation in millions"
               )
print(pop)

India         1444
China         1393
USA            323
Indoneasia     278
Name: Popoulation in millions, dtype: int64

In [9]:
q1=pd.Series({"Laptops":120,"Phones":340,"Tablets":77,})
q2=pd.Series({"Phones":44,"Laptops":474,"Watches":73,})
print(q1+q2)

Laptops    594.0
Phones     384.0
Tablets      NaN
Watches      NaN
dtype: float64

In [10]:
df = pd.DataFrame({
    "name":["Asha","Bill","Chen","Diya","Evan"],
    "Dept":["IT","HR","IT","FINANCE","HR"],
    "Salary":[52000,48000,47999,75000,50000],
    "City":["Delhi","Muambai","Suart","Agra","Delhi"],
})

In [11]:
print(df)

   name     Dept  Salary     City
0  Asha       IT   52000    Delhi
1  Bill       HR   48000  Muambai
2  Chen       IT   47999    Suart
3  Diya  FINANCE   75000     Agra
4  Evan       HR   50000    Delhi

In [12]:
print(df.shape,"\n")
print(list(df.columns),"\n")
df.info()
df.describe()

(5, 4)

['name', 'Dept', 'Salary', 'City']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   Dept    5 non-null      object
 2   Salary  5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

             Salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [13]:
df.head()

   name     Dept  Salary     City
0  Asha       IT   52000    Delhi
1  Bill       HR   48000  Muambai
2  Chen       IT   47999    Suart
3  Diya  FINANCE   75000     Agra
4  Evan       HR   50000    Delhi

In [14]:
raw= pd.DataFrame({
    "Order_Id":["1001","1002","1003"],
    "Amount":["2500","1800","3200"]
})

In [15]:
print(raw["Amount"].sum())

250018003200

In [16]:
clean = raw.copy()

In [17]:
clean["Order_Id"] = pd.to_numeric(clean["Order_Id"])
clean["Amount"] = pd.to_numeric(clean["Amount"])

In [18]:
print(raw)

  Order_Id Amount
0     1001   2500
1     1002   1800
2     1003   3200

In [19]:
print(clean.sum())

Order_Id    3006
Amount      7500
dtype: int64

In [20]:
df

   name     Dept  Salary     City
0  Asha       IT   52000    Delhi
1  Bill       HR   48000  Muambai
2  Chen       IT   47999    Suart
3  Diya  FINANCE   75000     Agra
4  Evan       HR   50000    Delhi

In [21]:
people = df.set_index("name")

In [22]:
people

         Dept  Salary     City
name
Asha       IT   52000    Delhi
Bill       HR   48000  Muambai
Chen       IT   47999    Suart
Diya  FINANCE   75000     Agra
Evan       HR   50000    Delhi

In [23]:
print(people.loc[["Asha"],["Salary"]])

      Salary
name
Asha   52000

In [24]:
print(people.iloc[1])

Dept           HR
Salary      48000
City      Muambai
Name: Bill, dtype: object

In [25]:
print(people.iloc[0:3],[0,2])

     Dept  Salary     City
name
Asha   IT   52000    Delhi
Bill   HR   48000  Muambai
Chen   IT   47999    Suart [0, 2]

In [26]:
print(people[people["Salary"]<49000])

     Dept  Salary     City
name
Bill   HR   48000  Muambai
Chen   IT   47999    Suart

In [27]:
print(people[(people["Dept"] == "IT")  & (people["Salary"]<49000)])

     Dept  Salary   City
name
Chen   IT   47999  Suart

In [29]:
print(people.query('Dept == "IT"'))

     Dept  Salary   City
name
Asha   IT   52000  Delhi
Chen   IT   47999  Suart

### MISSING DATA

In [37]:
messy = pd.DataFrame({
    "Product" : ["Pen","Book","Bag","Lamp","Mug"],
    "Price" : [20,np.nan,850,1200,np.nan],
    "Rating" : [4.1,4.5,np.nan,4.5,3.9]
})

In [38]:
messy

  Product   Price  Rating
0     Pen    20.0     4.1
1    Book     NaN     4.5
2     Bag   850.0     NaN
3    Lamp  1200.0     4.5
4     Mug     NaN     3.9

In [50]:
messy.isnull().sum()

Product    0
Price      2
Rating     1
dtype: int64

In [51]:
filled = messy.copy()

In [53]:
filled["Price"] = filled["Price"].fillna(filled["Price"].mean())

In [56]:
filled["Rating"] = filled["Rating"].fillna(filled["Rating"].mean())

In [57]:
print(filled)

  Product   Price  Rating
0     Pen    20.0    4.10
1    Book   690.0    4.50
2     Bag   850.0    4.25
3    Lamp  1200.0    4.50
4     Mug   690.0    3.90